backend/Modules/Invoices/Http/routes.php
<?php

Route::group(['middleware' => 'web','namespace' => 'Modules\Invoices\Http\Controllers'], function()
{
	//Route::get('/', 'InvoicesController@index');

	Route::resource('invoices','InvoicesController');
	Route::post('invoices/ajaxDetailPayment','InvoicesController@ajaxDetailPayment')->name('invoices.ajaxDetailPayment');
});

backend/Modules/Invoices/Entities/Invoice.php
<?php

namespace Modules\Invoices\Entities;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
	const INDEBT = 'in debt';
	const PAID = 'paid';

    protected $fillable = [];

    public function schedules(){
    	return $this->hasMany('\Modules\Schedules\Entities\Schedule','invoice_id');
    }

    public function order(){
    	return $this->belongsTo('\Modules\Transactions\Entities\Order','order_id');
    }

    public function customer(){
    	return $this->belongsTo('\Modules\Customers\Entities\Customer','customer_id');
    }

    public function payments(){
    	return $this->hasMany('Modules\Transactions\Entities\Payment','invoice_id');
    }

    public static function saveInvoice($id,$data){
    	\DB::beginTransaction();
    	try {
    		if(is_null($id)){
    			$invoice = new Invoice();
    		}else{
    			$invoice = Invoice::find($id);
    		}

    		$invoice->invoice_number = $data['invoice_number'];
    		$invoice->customer_id = $data['customer_id'];
    		$invoice->total_debt = $data['total_debt'];
    		$invoice->status = Invoice::INDEBT;

    		if(isset($data['order_id'])){
    			$invoice->order_id = $data['order_id'];
    		}
    		
    		$invoice->save();

    	} catch (\Exception $e) {
    		\DB::rollback();
    		return redirect()->route('invoices.index')->with('success','fail add new invoice');
    	}
    	\DB::commit();

    	return $invoice;
    }
}

backend/Modules/Invoices/Http/Controllers/InvoicesController.php
<?php

namespace Modules\Invoices\Http\Controllers;

use Nwidart\Modules\Routing\Controller;
use Modules\Invoices\Entities\Invoice;
use Modules\Schedules\Entities\Schedule;
use Modules\Transactions\Entities\Order;
use Modules\Customers\Entities\Customer;
use Modules\Transactions\Entities\Payment;
use Illuminate\Http\Request;

class InvoicesController extends Controller {

	public function index()
	{
		//Checking role for access customer page
		$current_user_role = $this->checkRole();
		if($current_user_role == 'notLogin'){
			return redirect()->route('login')->with('success','you dont have any authorization for access this page');
		}
		//=====================================
		$invoices = Invoice::with('customer','order.orderDetails')->get();

		return view('invoices::index',['invoices' => $invoices]);
	}

	public function create(){
		//Checking role for access customer page
		$current_user_role = $this->checkRole();
		if($current_user_role == 'notLogin'){
			return redirect()->route('login')->with('success','you dont have any authorization for access this page');
		}
		//=====================================

		$customers = Customer::all();
		return view('invoices::invoices.create',['customers' => $customers]);
	}


	public function store(Request $request){
		$data = $request->all();

		$invoice = Invoice::saveInvoice(null, $data);

		return redirect()->route('invoices.index')->with('success','successfully save invoice');
	}

	public function edit($id){
		//Checking role for access customer page
		$current_user_role = $this->checkRole();
		if($current_user_role == 'notLogin'){
			return redirect()->route('login')->with('success','you dont have any authorization for access this page');
		}
		//=====================================

		$invoice = Invoice::with('customer','order.orderDetails')->find($id);
		$customers = Customer::all();

		return view('invoices::invoices.edit',['invoice'=>$invoice, 'customers' => $customers]);
	}

	public function update($id,Request $request){
		$data = $request->all();
		$invoice = Invoice::saveInvoice($id,$data);

		return redirect()->route('invoices.index')->with('success','successfully edit invoice');
	}

	public function destroy($id){
		$invoice = Invoice::find($id);
		$invoice->delete();

		 return array(
            'url' => route('invoices.index'),
            'message' => 'Something went wrong while trying to remove the customer!'
        );
	}

	public function show($id){
		$invoice = Invoice::with(array('customer','payments'))->find($id);
		return view('invoices::invoices.details',['invoice' => $invoice]);
	}

	public function ajaxDetailPayment(Request $request){
		$data = $request->all();

		$payment = Payment::find($data['paymentId']);

		$payments['data'] = $payment;
		$payments['coords'] = json_decode($payment->coords);
		return $payments;
	}

	public function checkRole(){
		$user = \Sentinel::getUser();
		if($user){
            $current_user['superadmin'] = \Sentinel::inRole('superadmin');
            $current_user['admin'] = \Sentinel::inRole('admin');
            $current_user['sales'] = \Sentinel::inRole('sales');
            $current_user['gm'] = \Sentinel::inRole('gm');
            $current_user['bm'] = \Sentinel::inRole('bm');
            $current_user['debtCollector'] = \Sentinel::inRole('debtCollector');
            $current_user['customer'] = \Sentinel::inRole('customer');
			
			if($current_user['superadmin'] == true){
				return 'superadmin';
			}elseif($current_user['admin'] == true){
				return 'admin';
			}elseif($current_user['sales'] == true){
				return 'sales';
			}elseif($current_user['gm'] == true){
				return 'gm';
			}elseif($current_user['bm'] == true){
				return 'bm';
			}elseif($current_user['debtCollector'] == true){
				return 'debtCollector';
			}

		}else{
			return 'notLogin';
		}
	}

}

backend/Modules/Invoices/Resources/views/index.blade.php
@extends('layouts.app')
@section('header')

@parent
	
	<?php $success_message = session('success'); if($success_message){?>
		<script>
		jQuery(document).ready(function(){
			alert('<?php echo $success_message; ?>');
		});
		</script>
	<?php session()->forget('success'); } ?>
	
@endsection
@section('content')
				<!-- Page header -->
				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Invoices</span></h4>
						</div>
					</div>

					<div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li><a href="{{route('dashboard')}}"><i class="icon-home2 position-left"></i> Home</a></li>
							<li class="active">Invoices</li>
						</ul>
					</div>
				</div>
				<!-- /page header -->
				<div class="content">
					<div class="panel panel-flat">
					<table class="table datatable-basic">
					<thead>
						<tr>
							<th style="text-align:center;" >Id</th>
							<th style="text-align:center;" >Invoice Number</th>
							<th style="text-align:center;" >Customer</th>
							<th style="text-align:center;" >Total Debt</th>
							<th style="text-align:center;" >Total Paid</th>
							<th style="text-align:center;" >Status</th>
							<th style="text-align:center;" >Action</th>
						</tr>
					</thead>
					<tbody>	
						<?php if(isset($invoices)){ ?>
							<?php foreach($invoices as $invoice){?>
							<tr>
								<td style="text-align:center;" ><?php if($invoice->id){echo $invoice->id;}else{ echo '-';}?></td>
								<td style="text-align:center;" ><?php if($invoice->invoice_number){echo $invoice->invoice_number;}else{ echo '-';}?></td>
								<td style="text-align:center;" ><?php if($invoice->customer->name){echo $invoice->customer->name;}else{ echo '-';}?></td>
								<td style="text-align:center;" ><?php if($invoice->total_debt){echo number_format($invoice->total_debt,2);}else{ echo '-';}?></td>
								<td style="text-align:center;" ><?php if($invoice->total_paid){echo number_format($invoice->total_paid,2);}else{ echo '-';};?></td>
								<td style="text-align:center;" class="status"><?php if($invoice->status){echo $invoice->status;}else{ echo '-';}?></td>
								<td>
									<ul class="icons-list">
										<li >
											<a href="#" class="dropdown-toggle" data-toggle="dropdown">
												<i class="icon-cog7"></i>
												<span class="caret"></span>
											</a>
											<ul class="dropdown-menu dropdown-menu-right">
												<li class="dropdown-header">Options</li>
													<li><a href="{{route('invoices.show',$invoice->id)}}"><i class="icon-pencil7"></i>Details</a></li>
													<li><a href="{{route('invoices.edit',$invoice->id)}}"><i class="icon-pencil7"></i>Edit entry</a></li>
													<li><a href="{{ route('invoices.destroy', $invoice->id)}}" data-method="delete" data-token="{{ csrf_token() }}"><i class="icon-bin"></i>Remove entry</a></li>
											</ul>
										</li>
									</ul>
								</td>
							</tr>
							<?php } ?>
						<?php } ?>
					</tbody>
					</table>	
					</div>
				</div>

@endsection