backend/Modules/Products/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'namespace' => 'Modules\Products\Http\Controllers'], function()
{
	//Route::get('/', 'ProductsController@index');
	Route::get('products/createCategory','ProductsController@createCategory')->name('products.createCategory');
	Route::post('products/storeCategory','ProductsController@storeCategory')->name('products.storeCategory');
	Route::get('products/editCategory/{id}','ProductsController@editCategory')->name('products.editCategory');
	Route::put('products/updateCategory/{id}','ProductsController@updateCategory')->name('products.updateCategory');
	Route::delete('products/destroyCategory/{id}','ProductsController@destroyCategory')->name('products.destroyCategory');
	
	Route::get('products/uploadFile','ProductsController@uploadFile')->name('products.uploadFile');
	Route::post('products/storeFile','ProductsController@storeFile')->name('products.storeFile');
	Route::resource('products','ProductsController');

	Route::group(['middleware' => ['apiAuth'], 'prefix' => 'api/v1'], function() {
		Route::get('/products/getAll','ApiController@getAll');
	});
});

backend/Modules/Products/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Module Products</title>
	</head>
	<body>
		@yield('content')
	</body>
</html>

backend/Modules/Products/Resources/views/layouts/menu.blade.php
<?php $user = \Sentinel::getUser(); ?>
<?php //if($user != \Sentinel::inRole('sales')){ ?>
<?php if ($user->hasAccess(['products']) || $user->hasAccess('admin.login')){ ?>
<li>
	<a><i class="icon-users"></i><span>Products</span></a>
	<ul>
			<li><a href="{{route('products.index')}}">Products view</a></li>
			<li><a href="{{route('products.create')}}">Add Product</a></li>
			<li><a href="{{route('products.uploadFile')}}">Upload File</a></li>
			<li><a href="{{route('products.createCategory')}}">Add Category</a></li>
	</ul>
</li>
<?php } ?>