backend/Modules/Schedules/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'namespace' => 'Modules\Schedules\Http\Controllers'], function()
{
	//Route::get('/', 'SchedulesController@index');
	Route::resource('schedules','SchedulesController');
	Route::group(['middleware' => ['apiAuth'], 'prefix' => 'api/v1'], function() {
		Route::post('/schedules/getScheduleDebtCollector','ApiController@getScheduleDebtCollector');
		Route::post('/schedules/registerSchedule','ApiController@registerSchedule');
		Route::post('/schedules/editSchedule','ApiController@editSchedule');
		Route::post('/schedules/checkInSchedule','ApiController@checkInSchedule');
	});
});

backend/Modules/Schedules/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Module Schedules</title>
	</head>
	<body>
		@yield('content')
	</body>
</html>

backend/Modules/Schedules/Resources/views/layouts/menu.blade.php
<?php $user = \Sentinel::getUser(); ?>
<?php //if($user == \Sentinel::inRole('superadmin') || $user == \Sentinel::inRole('admin')){?>
<?php if ($user->hasAccess(['schedules']) || $user->hasAccess('admin.login')){ ?>
<li>
	<a><i class="icon-users"></i> <span>Schedules</span></a>
	<ul>
			<li><a href="{{route('schedules.index')}}">Schedules view</a></li>
			<li><a href="{{route('schedules.create')}}">Add Schedule</a></li>
	</ul>
</li>
<?php } ?>